### PR TITLE
:sparkles: Fix icon on column's header

### LINKED ISSUE #146: [Database] Fix icon on column's header + Update cursor if column is not editable
Currently, to select the column icon in the table header,  the original column is used, which is strange because the user cannot understand why this column is not editable (among other things)

### PR DESCRIPTION
**Pull request by Alketta**
Closes #146

### CODE REVIEW

File: front/src/services/lck-utils/columns.ts [hunk 1]
```diff
@@ -214,8 +214,7 @@ export function getOriginalColumn (column: LckTableColumn): LckTableColumn {
 }
 
 export function getColumnClass (column: LckTableViewColumn): string {
-  const columnClass = getColumnTypeId(column)
-  switch (columnClass) {
+  switch (column.column_type_id) {
```
Comment (mdartic) [inline front/src/services/lck-utils/columns.ts:217]: If you remove the call to `getColumnTypeId`, we won't be able to know the "original" type of a lookup column / vlookup.
Is this what you really want to do ?
And I think the icon displayed in the column header will be empty.

Comment (Alketta) [reply front/src/services/lck-utils/columns.ts:217]: For more understanding

Actually with have this: 
withOrigin

With this MR will we have:
withoutOrigin

The difference is that now we can see that the column is a FORMULA and so understand why it is not modifiable (same for LOOKED_UP_COLUMN)

Comment (mdartic) [reply front/src/services/lck-utils/columns.ts:217]: I understand your point, but I'm not sure how to display it, as I find the information useful.
But, well, this seems a good way to inform the user for the editable - or not - state of the field !

**Review by mdartic — APPROVED** [review]
