### PR TITLE
:beetle: Remove trim on input text + Refacto and Fix typo in file

### LINKED ISSUE #113: [Account] Impossible to add white space when we create/edit an user

### PR DESCRIPTION
**Pull request by Alketta**
Closes #113

### CODE REVIEW

File: front/src/views/routes/admin/UserManagement.vue [hunk 1]
```diff
@@ -424,7 +424,7 @@ export default {
           await lckClient.service('user').patch(userId, {
             name: this.user.name,
             profile: this.user.profile,
-            email: this.user.email,
+            email: (this.user.email).trim(),
```
Comment (mdartic) [inline front/src/views/routes/admin/UserManagement.vue:427]: Do you think it could be nicer to use the `v-model.trim` in the html ?

**Review by mdartic — APPROVED** [review]
