### PR TITLE
:art: Remove box shadow + Fix size for container of map

### LINKED ISSUE #122: [UX-UI] Improve css print
- [ ] : Remove box-shadow on container
- [ ] : Improve on map

### PR DESCRIPTION
**Pull request by Alketta**
Close #122

### CODE REVIEW

File: front/src/views/routes/common/cms/CommonCMSPage.vue [hunk 1]
```diff
@@ -1210,11 +1213,18 @@ export default {
...
+    display: block !important;
   }
 
   .lck-container > div {
-    display: block !important;
     height: auto;
+    box-shadow: unset;
+  }
+
+  .lck-container > :not(.lck-container-active) ::v-deep .map-container {
```
Comment (mdartic) [inline front/src/views/routes/common/cms/CommonCMSPage.vue:1224]: Could you explain why only the containers that are inactive ?
Could you add some visual tests for these use cases ?

Comment (Alketta) [reply front/src/views/routes/common/cms/CommonCMSPage.vue:1224]: > Could you explain why only the containers that are inactive?

Case for page with anchor or tabs.

The initial problem: When printing the pdf, the position of the scale and attribution is shifted in regard to the map.

Because of css in DataRecord.

Map container takes the same size (width) as the other fields. Therefore, the map canvas is updated.

But as the other containers are set to `display: none`, the map canvas is set to the default size. So, when switching to pdf print mode, the map container is resized to the size defined by DataRecord but the canvas is not resized.

The solution is therefore for the active container to display the map with a size adapted to DataRecord (because if you reduce the size, the map is no longer correct) and for the other containers to have a reduced size corresponding to the default one.

>  Could you add some visual tests for these use cases?

Storybook allow to take snapshot with print css?

Comment (mdartic) [reply front/src/views/routes/common/cms/CommonCMSPage.vue:1224]: Great, I understand better.
I think we can do it by specifying new devices, but I didn't find if we could create a "print" one.
So, maybe just add comments in the code to remember why you did this ?

Comment (Alketta) [reply front/src/views/routes/common/cms/CommonCMSPage.vue:1229]: Done

**Review by mdartic — APPROVED** [review]
