### PR TITLE
Fix tab

### LINKED ISSUE #88: [Visu]  Improve tabs
- Fix submit when we select a navigation mode
- Improve default anchor for each navigation mode if navigation true
- Fix last anchor/tabs which causes the navigation bar to disappear

### PR DESCRIPTION
**Pull request by Alketta**
Fixes #88

### CODE REVIEW

File: front/src/components/visualize/UpdateSidebar/UpdatePageForm/UpdatePageForm.vue [hunk 1]
```diff
@@ -143,6 +148,20 @@ export default Vue.extend({
     onFormSubmit () {
       return this.$emit('updateModeNavigation', this.modeNavigation)
     },
+    radioChange (value: string, validate: Function) {
+      if (value !== this.modeNavigation) {
+        this.modeNavigation = value
+        validate(value);
+        // setFlags belongs to ValidationProvider which extend Element
+        // eslint-disable-next-line @typescript-eslint/no-explicit-any
+        (this.$refs['vp-mode-navigation'] as any).setFlags({
```
Comment (mdartic) [inline front/src/components/visualize/UpdateSidebar/UpdatePageForm/UpdatePageForm.vue:157]: Is it possible to cast `as ValidationProvider` ?

File: front/src/views/routes/common/cms/CommonCMSPage.vue [hunk 2]
```diff
@@ -27,18 +27,19 @@
 
       <div class="lck-container-parent p-mx-2">
         <div
-          v-for="container in displayContainersByModeNavigation"
+          v-for="container in this.page.containers"
```
Comment (mdartic) [inline front/src/views/routes/common/cms/CommonCMSPage.vue:30]: Why did you remove the `displayContainersByModeNavigation` ?

File: front/src/views/routes/common/cms/CommonCMSPage.vue [hunk 3]
```diff
@@ -27,18 +27,19 @@
...
           class="lck-container"
           :class="{
             'lck-elevation': container.elevation
           }"
         >
-          <h2 v-if="container.display_title" class="lck-color-title">
+          <div v-show="container.id === currentHash">
+            <h2 v-if="container.display_title" class="lck-color-title">
             {{ container.text }}
           </h2>
```
Comment (mdartic) [inline front/src/views/routes/common/cms/CommonCMSPage.vue:41]: Could you increment correctly this line ?

File: front/src/views/routes/common/cms/CommonCMSPage.vue (hunk 2 above)
Comment (Alketta) [reply front/src/views/routes/common/cms/CommonCMSPage.vue:30]: Because now, we have a v-show

File: front/src/views/routes/common/cms/CommonCMSPage.vue [hunk 4]
```diff
@@ -305,9 +310,13 @@ export default {
       this.currentBlockToEdit = null
       this.showUpdateSidebar = true
     },
-    async forceHashToNavigate () {
-      if (this.page.modeNavigation === 'tab' && this.page.containers.length > 0) {
-        if (!this.$route.hash) {
+    async forceHashToNavigate (route) {
+      if (this.isNavBarAnchorLinkDisplayed && this.page.containers.length > 0) {
```
[the remark this answers is not in the document]
Comment (Alketta) [reply front/src/views/routes/common/cms/CommonCMSPage.vue]: You are right

**Review by mdartic — APPROVED** [review]
